#!/bin/bash

# 2013.01.30 Cédric Briner: add function : stdout_n_stderr_2_log

set  -e ; # errexit	Abort script at first error, when a command exits with
          # non-zero status (except in until or while loops, if-tests,
          # list constructs)
export PATH="/bin:/usr/bin:/usr/sbin:/usr/local/bin"

LOG_PATH=/var/log/tzm-sched.log
INCLUDE_EXCLUDE=/opt/tivoli/tsm/client/ba/bin/include_exclude_backup
IS_VERBOSE=0

EMAIL_DEST="unix-bot@unige.ch"

DOLLY_MOUNTPOINT=/dolly/backup
DOLLY_CLONE_ARGS_DEFAULT="${DOLLY_MOUNTPOINT}"
unset DOLLY_CLONE_ARGS_4_ZONENAME
declare -A DOLLY_CLONE_ARGS_4_ZONENAME
DOLLY_CLONE_ARGS_4_ZONENAME["global"]="${DOLLY_MOUNTPOINT} --zpool-name-incl=rpool --sub-zfs-dir-incl="

DSMC_ERROR_RE='( ANS[[:alnum:]]{5} |No schedule returned from server.)'
DSMC_ERROR_OK_RE=' ANS(1898I|1696W|1115W|1149E|1809W|2200I|2201I|2820E|1484I) '
#  ANS1898I   TSM has processed the specified number of files
#  ANS1696W   Objects were excluded from backup because the file system file-system-name is excluded from backup or archive processing.
#  ANS1115W   EXCLUDE.DIR You can not back up, archive, or migrate files that are excluded
#  ANS1149E   EXCLUDE.FS  You can not back up, archive, or migrate files that are excluded
#  ANS1809W   An session with the TSM server has been disconnected. An attempt will be made to reestablish the connection.
#  ANS2200I   Filling cache (memory efficient)
#  ANS2201I   Inspecting cache (memory efficient)
#  ANS2820E   An interrupt has occurred. The current operation will end and the client will shut down.
#  ANS1484I   Schedule log pruning finished successfully.



test -f /usr/local/bin/tzm-sched.conf && source /usr/local/bin/tzm-sched.conf

mailx_utf-8()
# mailx_utf-8 is a sort of mailx which support utf-8
{
    SUBJECT=""
    while [[ "$1" = -* ]]; do
      case "$1" in
        -s|--subject)
          SUBJECT=$2
          shift 2
          ;;
      esac
    done
    RECIPIENTS="$@"
    {
        cat << EOF
From: unix-bot@unige.ch
To: ${RECIPIENTS}
Subject: ${SUBJECT}
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
EOF
       cat -    
    } | /usr/sbin/sendmail ${RECIPIENTS} 
}

delete_metadata4archive()
{   
    if test -d /tmp/tzm-sched/metadata4archive ; then
        rm -f /tmp/tzm-sched/metadata4archive/date
        rm -f /tmp/tzm-sched/metadata4archive/hostname
        rm -f /tmp/tzm-sched/metadata4archive/ifconfig_-a
        rm -f /tmp/tzm-sched/metadata4archive/zpool_status.out
        rm -f /tmp/tzm-sched/metadata4archive/zpool_list.out
        rm -f /tmp/tzm-sched/metadata4archive/beadm_list_-d.out
        rm -f /tmp/tzm-sched/metadata4archive/zfs_get_-rHp_all.out
        rm -f /tmp/tzm-sched/metadata4archive/zfs_list_-t_filesystem.out
        rmdir /tmp/tzm-sched/metadata4archive
    fi
    for mnt4copy in $(zfs get -H ch.unige.dolly:zone \
        | gawk '{if ( $3 == "-" ){ print $1} }' \
        | grep -v "@" \
        | gxargs --no-run-if-empty zfs get -H mounted | ggrep -P "\tyes\t" | cut -f1 \
        | gxargs --no-run-if-empty zfs get -H mountpoint | cut -f3) ; do
        rm -f ${mnt4copy}/.metadata4archive.tgz
    done
    rm -f /tmp/tzm-sched/metadata4archive.tgz
    if test -d /tmp/tzm-sched; then
        rmdir /tmp/tzm-sched
    fi
}

#
# a tool which write down stuff that we can not see in a regular backup
write_metadata4archive()
{
    delete_metadata4archive
    #
    
    mkdir -p /tmp/tzm-sched/metadata4archive
    date +"%Y/%m/%d-%H:%M" >/tmp/tzm-sched/metadata4archive/date
    hostname > /tmp/tzm-sched/metadata4archive/hostname
    ifconfig -a > /tmp/tzm-sched/metadata4archive/ifconfig_-a
    zpool status > /tmp/tzm-sched/metadata4archive/zpool_status.out
    zpool list > /tmp/tzm-sched/metadata4archive/zpool_list.out
    beadm list -d > /tmp/tzm-sched/metadata4archive/beadm_list_-d.out
    zfs get -rHp all > /tmp/tzm-sched/metadata4archive/zfs_get_-rHp_all.out
    zfs list -t filesystem > /tmp/tzm-sched/metadata4archive/zfs_list_-t_filesystem.out
    cd /tmp/tzm-sched
    gtar -czvf metadata4archive.tgz ./metadata4archive > /dev/null
    cd - > /dev/null
    
    #
    # COPY this file in every mountpoint that will be backep up
#    # - write a file of re based on which mountpoint is excluded from backup
#    #   /tmp/tzm-sched/exclude-mountpoint-re
#    # - write a file listing the mountpoint that will be backed up
#    #   /tmp/tzm-sched/include-mountpoint
#    cat /opt/tivoli/tsm/client/ba/bin/include_exclude_backup \
#    | grep exclude.fs | cut -d " " -f2 \
#    | gsed -e 's|^|^|' -e 's|$|$|' > /tmp/tzm-sched/exclude-mountpoint-re
#    #
#    zfs list -H -t filesystem -r -o mountpoint | ggrep "^/" \
#    | ggrep -vf /tmp/tzm-sched/exclude-mountpoint-re > /tmp/tzm-sched/include-mountpoint
    for mnt4copy in $(zfs get -H ch.unige.dolly:zone \
        | gawk '{if ( $3 == "-" ){ print $1} }' \
        | grep -v "@" \
        | gxargs --no-run-if-empty zfs get -H mounted | ggrep -P "\tyes\t" | cut -f1 \
        | gxargs --no-run-if-empty zfs get -H mountpoint | cut -f3) ; do
        cp /tmp/tzm-sched/metadata4archive.tgz ${mnt4copy}/.metadata4archive.tgz | :
    done

}


echo_verbose()
{
	if test ${IS_VERBOSE} -eq 1 ; then
		echo $@
	fi 
}

write_include_exclude_4_tsm()
{
    {
        echo "* include/exclude file generated for dolly_mountpoint:"
        echo "*  - ${DOLLY_MOUNTPOINT}"
        echo "* by tzm-sched"
        #
        # EXCLUDE fs which are in both origin & clone from the original
        #   -1- take the ZFS belonging to this zonename
        #   -2- keep the one with the same dolly_mounpoint
        #   -3- remove the snapshots
        #   -4- keep the one wich are mounted
        #   -5- find the ZFS they were originated from
        #   -6- find their mountpoint
        #   -7- do an exclude.fs for tsm
        echo "*"
        echo "* EXCLUDE ZFS which are in both origin & clone from the original"
        zfs get -H ch.unige.dolly:zone | ggrep -P "\t$(zonename)\t" | cut -f1 \
        | gxargs --no-run-if-empty zfs get -H ch.unige.dolly:mountpoint | ggrep -P "\t${DOLLY_MOUNTPOINT}\t" | cut -f1 \
        | grep -v "@"  \
        | gxargs --no-run-if-empty zfs get -H mounted | ggrep -P "\tyes\t" | cut -f1 \
        | gxargs --no-run-if-empty zfs get -H origin | cut -f3 | cut -d "@" -f1 \
        | gxargs --no-run-if-empty zfs get -H mountpoint | cut -f3 \
        | gsed 's|\(.*\)|exclude.fs \1|'
        #
        # EXCLUDE fs which are in other "dolly clone" in the same zonename
        #   -1- take the ZFS belonging to this zonename
        #   -2- remove the one with the same dolly_mounpoint
        #   -3- remove the snapshots
        #   -4- keep the one wich are mounted
        #   -5- find their mountpoint
        #   -6- do an exclude.fs for tsm
        echo "*"
        echo "* EXCLUDE ZFS which are in other \"dolly clone\" in the same zonename"
        zfs get -H ch.unige.dolly:zone | ggrep -P "\t$(zonename)\t" | cut -f1 \
        | gxargs --no-run-if-empty zfs get -H "ch.unige.dolly:mountpoint" | ggrep -Pv "\t${DOLLY_MOUNTPOINT}\t" | cut -f1 \
        | grep -v "@" \
        | gxargs --no-run-if-empty zfs get -H mounted | ggrep -P "\tyes\t" | cut -f1 \
        | gxargs --no-run-if-empty  zfs get -H mountpoint | cut -f3 \
        | gsed 's|\(.*\)|exclude.fs \1|'
        #
        # EXCLUDE fs which are in other zone
        #   -1- take the ZFS which are zoned
        #   -2- remove the snapshots
        #   -3- keep the one wich are mounted
        #   -4- find their mountpoint
        #   -5- do an exclude.fs for tsm
        echo "*"
        echo "* EXCLUDE ZFS which are in other zone"
        if test "$(zonename)" == "global" ; then
            zfs get -H zoned | ggrep -P "\ton\t" | cut -f1 \
            | grep -v "@"  \
            | gxargs --no-run-if-empty zfs get -H mounted | ggrep -P "\tyes\t" | cut -f1 \
            | gxargs --no-run-if-empty  zfs get -H mountpoint | cut -f3 \
            | gsed 's|\(.*\)|exclude.fs \1|'
        fi
        #
        # EXCLUDE system/volatile
        echo "*"
        echo "* EXCLUDE swap FS mounted on */system/volatile"
        mount | grep " swap " | cut -d " " -f1 | ggrep -E '/system/volatile$' \
              | gsed 's|\(.*\)|exclude.fs \1|'
#        #
#        # INCLUDE /tmp
#        echo "*"
#        echo "* INCLUDE /tmp"
#        echo "include.fs /tmp"
        
    } > ${INCLUDE_EXCLUDE}
}

start-service()
{
   echo enter start-service
   echo nothing to do in start-service
   echo exit start-service
}

stop_service()
{
   echo enter stop-service
   echo nothing to do in stop-service
   echo exit stop-service
}

pre()
{
    echo_verbose "------------"
    echo_verbose enter pre-tsm
    echo_verbose "------------"
    #
    # check that dsm-sched is disabled
    echo_verbose -n "check dsmc scheduler & dolly…"
    if ! svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
        echo -e "\n✘ dsmc-sched should be disabled ✘"
        echo "hint: clean $(basename $0) with $(basename $0) clean"
        exit 1
    fi
    #
    # check that dolly is not mounted
    if /usr/local/bin/dolly | ggrep -q "^mounted ${DOLLY_MOUNTPOINT}" ; then
        echo "\n✘ dolly should not be mounted ✘"
        echo "hint: clean $(basename $0) with $(basename $0) clean"
        exit 2
    fi
    echo_verbose " ✔"
    #
    # dolly it
    echo_verbose -n "write metadata for archive… "
    write_metadata4archive
    echo_verbose " ✔"
    echo_verbose -n "create the clone…"
    if test -n "${DOLLY_CLONE_ARGS_4_ZONENAME[$(zonename)]}" ; then
        /usr/local/bin/dolly clone ${DOLLY_CLONE_ARGS_4_ZONENAME[$(zonename)]}
    else
        /usr/local/bin/dolly clone ${DOLLY_CLONE_ARGS_DEFAULT}
    fi
    echo_verbose " ✔"
    echo_verbose -n "delete metadata for archive…"
    delete_metadata4archive
    echo_verbose " ✔"
    #
    # write the include exclude file
    echo_verbose -n "write the include exclude file…"
    write_include_exclude_4_tsm
    echo_verbose " ✔"
    
    #
    # enable dsm-sched
    echo_verbose -n " check if dsmc-sched enabled…"
    svcadm enable -s dsmc-sched:default
    if ! svcs -H dsmc-sched:default | ggrep -q '^online ' ; then
        echo "\n✘ dsmc-sched should be enabled after a 'svcadm enable -s dsmc-sched:default' ✘"
        exit 3
    fi
    echo_verbose " ✔"
    #
    #    
    echo_verbose "------------"
    echo_verbose exit pre-tsm
    echo_verbose "------------"
}

clean()
{
    echo "----------"
    echo enter clean
    echo "----------"
    #
    # dolly kill
    echo "check if a clone is present"
    if /usr/local/bin/dolly | ggrep -q "^mounted ${DOLLY_MOUNTPOINT}" ; then
      echo -n " present! let's kill it…"
      /usr/local/bin/dolly kill ${DOLLY_MOUNTPOINT}
      if /usr/local/bin/dolly | ggrep -q "^mounted ${DOLLY_MOUNTPOINT}" ; then
        echo "\n✘ unable to kill it"
      else
        echo " ✔"
      fi
    else
      echo " ✔ not present"
    fi
    #
    # disable dsmc-sched
    echo "check if dsmc-sched is running…"
    if ! svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
        echo -n " running! let's stop it…"
        svcadm disable -s dsmc-sched
      if svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
        echo " ✔"
      else
        echo "\n✘ unable to stop it"
      fi
    else
      echo " ✔ not running"
    fi
    #
    # remove directories
    echo "check if the dir(${DOLLY_MOUNTPOINT}) exists"
    if test -d ${DOLLY_MOUNTPOINT} ; then
      if test -z "$(gfind ${DOLLY_MOUNTPOINT} ! -type d)" ; then
        echo " ✘ no… but the dir(${DOLLY_MOUNTPOINT}) is constitued only of nested empty dir."
        echo "   So, you can safely destroy them with : rm -fr ${DOLLY_MOUNTPOINT}"
      else
        echo " ✘ ouch, it seems that the mountpoint (${DOLLY_MOUNTPOINT}) is mounted."
        echo "   This directory should not exist."
        echo "   Please remove this mountpoint(${DOLLY_MOUNTPOINT}) carefully"
      fi
    else
      echo " ✔ does not exists"
    fi
    #
    # remove lock
    echo "check if the lock (${DOLLY_MOUNTPOINT}.lock) is present"
    if test -f ${DOLLY_MOUNTPOINT}.lock ; then
      echo -n " it is. Let's remove it…"
      if rm ${DOLLY_MOUNTPOINT}.lock ; then
        echo " ✔"
      else
        echo "\n ✘ unable to remove the lock(${DOLLY_MOUNTPOINT}.lock)"
      fi
    else
      echo " ✔ not present"
    fi
    echo "----------"
    echo "exit clean"
    echo "----------"
}

post()
{
    echo_verbose "------------"
    echo_verbose enter post-tsm
    echo_verbose "------------"
    #
    # dolly kill
    echo_verbose -n "kill the clone…"
    /usr/local/bin/dolly kill ${DOLLY_MOUNTPOINT}
    echo_verbose " ✔"
    #
    # Parse the log and rotate it
    echo_verbose -n "parse the log and rotate it…"
    body_email=$(mktemp -p /tmp tzm-sched-email.XXXXXX)
    gegrep "${DSMC_ERROR_RE}" /var/log/dsmsched.log | gegrep -v "${DSMC_ERROR_OK_RE}" | cat > ${body_email}
    logadm -f /dev/null -C10 -N -t '$file.%Y-%m-%d_%H:%M:%S' /var/log/dsmsched.log
    echo_verbose " ✔"
    echo_verbose -n "check the log to see if errors occured during the last backup…"
    if test -s ${body_email} ; then
        echo_verbose "\n ✘ error occured, better check them ✘"
        if test ${IS_VERBOSE} -eq 1 ; then
          cat ${body_email} | sed "s|^|   - |"
        fi
    else
      echo_verbose " ✔ no errors"
    fi
    #
    # send email
    echo_verbose -n "send email…"
    if test -s ${body_email} ; then
        cat ${body_email} | mailx_utf-8 -s "[$(hostname)] TSM Backup" ${EMAIL_DEST}
        echo_verbose " ✔ sent"
    else
        echo_verbose " ✔ not needed"
    fi
    rm ${body_email}
    #
    # disable dsmc-sched
    echo_verbose 'tell "at" to disable dsmc-sched in 1 minute'
    env SHELL=/bin/bash at 'now + 1minutes' << EOF_AT
export PATH="/usr/bin:/usr/sbin:/usr/local/bin"
svcadm disable -s dsmc-sched
if ! svcs -H dsmc-sched:default | ggrep -q '^disabled ' ; then
    echo "the \"at\" jobs from \"tzm-sched\" was unable to stop the dsmc-sched" | mailx -s "[$(hostname | cut -d "." -f1)] TSM Backup" ${EMAIL_DEST}
    exit 3
fi
EOF_AT
    #
    #
    echo_verbose "------------"
    echo_verbose exit post-tsm
    echo_verbose "------------"
}

stdout_n_stderr_2_log()
{   
    # http://serverfault.com/questions/103501/how-can-i-fully-log-all-bash-scripts-actions
    exec 3>&1 4>&2
    trap 'exec 2>&4 1>&3' 0 1 2 3
    exec 1> >(while read line ; do  echo -n $(date +"%Y.%m.%d-%H:%M:%S") ;echo " - $$ - info - $line" ; done>>${LOG_PATH})
    exec 2> >(while read line ; do  echo -n $(date +"%Y.%m.%d-%H:%M:%S") ;echo " - $$ - error -$line" ; done>>${LOG_PATH})
}


usage () {
	scriptname=$(basename ${0})
   cat <<EOF
Usage: $scriptname pre-tsm | post-tsm
       $scriptname clean
       $scriptname [-d] write_metadata4archive | delete_metadata4archive
   -h   displays basic help
   -v   verbose
   -l   stdout and stderr to \$LOG_PATH(${LOG_PATH})

- pre-tsm/post-tsm are to be invoked if you want to backup with a scheduler
in mind

- clean is to be invoked when something get wrong and that it removes the well known problem
EOF
   exit 0
}
IS_VERBOSE=0
while getopts ":vhl" opt; do
  case $opt in
    v)
      IS_VERBOSE=1
      ;;
    h)
      usage
      ;;
    l)
      stdout_n_stderr_2_log
      ;;
    *)
      usage
      ;;
  esac
done


shift $((OPTIND-1))

if (( $# != 1 )) ; then
  usage
fi

case $1 in
   pre)
     pre
     ;;
   pre-tsm)
     pre
     ;;
   post)
     post
     ;;
   post-tsm)
     post
     ;;
   clean)
     clean
     ;;
   write_metadata4archive)
     write_metadata4archive
     ;;
   delete_metadata4archive)
     delete_metadata4archive
     ;;
   *)
     usage
     ;;
esac
