#!/sbin/sh
#
# SMF methods for TSM client
#
# Ian Chard <ian.chard@sers.ox.ac.uk>
#

. /lib/svc/share/smf_include.sh

if /usr/bin/pgrep -x -u 0 -z `/sbin/zonename` dsmc >/dev/null 2>&1
then
	echo "$0: dsmc sched already running"
	exit $SMF_EXIT_ERR_NOSMF
fi

if [ -x /usr/bin/dsmc ]; then
	/usr/bin/dsmc sched >/dev/null 2>&1 &
else
	exit 1
fi

exit $SMF_EXIT_OK
