#!/bin/bash
#
# this script helps people managing oracle DB at UNIGE easily manage their 
# backup. It is not intended to be used outside of UNIGE
#
# doc:
# extglob :
#  - http://stackoverflow.com/questions/216995/how-can-i-use-inverse-or-negative-wildcards-when-pattern-matching-in-a-unix-linu
#  - http://www.linuxjournal.com/content/bash-extended-globbing

shopt -s extglob

EMAIL_DEST="unixbot and dbadinf"

EXCLUDE_PATH_GENERATED=/opt/tivoli/tsm/client/ba/bin/exclude_extra_4_db_node
ZFS_MOUNTPOINT_NO_DOLLY_PATH=/var/run/mountpoint_nodolly
#
# is there some new ZFS to take in account
tmp_mountpoint_nodolly=$(mktemp -p /tmp $(basename ${ZFS_MOUNTPOINT_NO_DOLLY_PATH}).XXXXXX)
#
#   -1- take the ZFS not created by dolly
#   -2- remove the snapshots
#   -4- keep the one wich are mounted
#   -6- find their mountpoint
zfs get -H ch.unige:created_by | ggrep -vP "\tdolly\t" | cut -f1 \
 | grep -v "@" \
 | gxargs --no-run-if-empty zfs get -H mounted | ggrep -P "\tyes\t" | cut -f1 \
 | gxargs --no-run-if-empty zfs get -H mountpoint | cut -f3 >  ${tmp_mountpoint_nodolly}

if ! gdiff -q  ${tmp_mountpoint_nodolly} ${ZFS_MOUNTPOINT_NO_DOLLY_PATH} > /dev/null 2>&1 ; then
    #
    # rotate mountpoint_nodolly and push the new one 
    logadm  -f /dev/null -N ${ZFS_MOUNTPOINT_NO_DOLLY_PATH}
    mv ${tmp_mountpoint_nodolly} ${ZFS_MOUNTPOINT_NO_DOLLY_PATH}
    #
    # rotate the exclude_dolly and generate the new one
    logadm  -f /dev/null -N ${EXCLUDE_PATH_GENERATED}
    {
        echo "*"
        echo "* exclude the mountpoint in /oracle except the /oracle/app"
        cat ${ZFS_MOUNTPOINT_NO_DOLLY_PATH} \
        |  ggrep -E "($(echo /oracle/!(app) | tr -s " " "|"))"
        echo "*"
        echo "* exclude every possible mountpoint behind a dolly"
        for mountpoint in $(ls -1 /oracle/  | grep -v app) ; do
            echo "* - for dolly(/dolly/${mountpoint})"
            cat ${ZFS_MOUNTPOINT_NO_DOLLY_PATH} | sed "s|^|exclude.fs /dolly/${mountpoint}|"
        done
    } > ${EXCLUDE_PATH_GENERATED}
    #
    # send messages
    mailx -s "[$(hostname| cut -d '.' -f1)] $(basename $0): zfs list as changed" $EMAIL_DEST <<EOF
zfs list as changed, so we have to reflect the change on how the backup is
configured.

We've created the new ${EXCLUDE_PATH_GENERATED} which is somehow included in a dsm.sys
EOF
else
    rm ${tmp_mountpoint_nodolly}
fi